[E]	manager_10@10.16.2.223	2018-10-18 11:00:02.18445 +0800	1539831602	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:02.19166 +0800	1539831602	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:02.19331 +0800	1539831602	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.14954.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:07.20297 +0800	1539831607	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:07.20822 +0800	1539831607	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:07.52324 +0800	1539831607	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_10@10.16.2.223	2018-10-18 11:00:07.52533 +0800	1539831607	null:null	0	CRASH REPORT Process <0.15027.18> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_10@10.16.2.223	2018-10-18 11:00:07.52696 +0800	1539831607	null:null	0	Supervisor leo_rpc_client_manager_1_at_13095_sup had child leo_rpc_client_manager_1_at_13095 started with leo_pod_manager:start_link(leo_rpc_client_manager_1_at_13095, 16, 16, leo_rpc_client_conn, [manager_1,"10.0.1.102",13095,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_10@10.16.2.223	2018-10-18 11:00:07.52825 +0800	1539831607	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.14978.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[W]	manager_10@10.16.2.223	2018-10-18 11:00:07.52991 +0800	1539831607	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_1_at_13095,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_1_at_13095,{leo_pod_sup,start_link,[leo_rpc_client_manager_1_at_13095,16,16,leo_rpc_client_conn,[manager_1,"10.0.1.102",13095,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_10@10.16.2.223	2018-10-18 11:00:12.54502 +0800	1539831612	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:12.54996 +0800	1539831612	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:12.55150 +0800	1539831612	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15030.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:17.56402 +0800	1539831617	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:17.56787 +0800	1539831617	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:17.56952 +0800	1539831617	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15057.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:22.58421 +0800	1539831622	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:22.58955 +0800	1539831622	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:22.59134 +0800	1539831622	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15102.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:27.60404 +0800	1539831627	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:27.60940 +0800	1539831627	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:27.89567 +0800	1539831627	null:null	0	CRASH REPORT Process <0.15173.18> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_10@10.16.2.223	2018-10-18 11:00:27.89897 +0800	1539831627	null:null	0	Supervisor leo_rpc_client_manager_1_at_13095_sup had child leo_rpc_client_manager_1_at_13095 started with leo_pod_manager:start_link(leo_rpc_client_manager_1_at_13095, 16, 16, leo_rpc_client_conn, [manager_1,"10.0.1.102",13095,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_10@10.16.2.223	2018-10-18 11:00:27.90016 +0800	1539831627	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15124.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[W]	manager_10@10.16.2.223	2018-10-18 11:00:27.90137 +0800	1539831627	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_1_at_13095,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_1_at_13095,{leo_pod_sup,start_link,[leo_rpc_client_manager_1_at_13095,16,16,leo_rpc_client_conn,[manager_1,"10.0.1.102",13095,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_10@10.16.2.223	2018-10-18 11:00:32.91460 +0800	1539831632	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:32.91758 +0800	1539831632	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:32.91915 +0800	1539831632	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15175.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:37.93414 +0800	1539831637	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:37.93769 +0800	1539831637	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:37.93936 +0800	1539831637	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15202.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:42.95484 +0800	1539831642	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:42.95835 +0800	1539831642	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:42.96016 +0800	1539831642	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15250.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:47.97387 +0800	1539831647	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:47.97746 +0800	1539831647	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:47.127057 +0800	1539831647	null:null	0	CRASH REPORT Process <0.15344.18> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_10@10.16.2.223	2018-10-18 11:00:47.127266 +0800	1539831647	null:null	0	Supervisor leo_rpc_client_manager_1_at_13095_sup had child leo_rpc_client_manager_1_at_13095 started with leo_pod_manager:start_link(leo_rpc_client_manager_1_at_13095, 16, 16, leo_rpc_client_conn, [manager_1,"10.0.1.102",13095,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_10@10.16.2.223	2018-10-18 11:00:47.127382 +0800	1539831647	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15296.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[W]	manager_10@10.16.2.223	2018-10-18 11:00:47.127499 +0800	1539831647	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_1_at_13095,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_1_at_13095,{leo_pod_sup,start_link,[leo_rpc_client_manager_1_at_13095,16,16,leo_rpc_client_conn,[manager_1,"10.0.1.102",13095,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_10@10.16.2.223	2018-10-18 11:00:52.128414 +0800	1539831652	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:52.128770 +0800	1539831652	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:52.128933 +0800	1539831652	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15346.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:00:57.130558 +0800	1539831657	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:00:57.130874 +0800	1539831657	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:00:57.131021 +0800	1539831657	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15371.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:02.132461 +0800	1539831662	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:02.132788 +0800	1539831662	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:02.132970 +0800	1539831662	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15418.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:07.134396 +0800	1539831667	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:07.134735 +0800	1539831667	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:07.165233 +0800	1539831667	null:null	0	CRASH REPORT Process <0.15495.18> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_10@10.16.2.223	2018-10-18 11:01:07.165433 +0800	1539831667	null:null	0	Supervisor leo_rpc_client_manager_1_at_13095_sup had child leo_rpc_client_manager_1_at_13095 started with leo_pod_manager:start_link(leo_rpc_client_manager_1_at_13095, 16, 16, leo_rpc_client_conn, [manager_1,"10.0.1.102",13095,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_10@10.16.2.223	2018-10-18 11:01:07.165567 +0800	1539831667	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15445.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[W]	manager_10@10.16.2.223	2018-10-18 11:01:07.165681 +0800	1539831667	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_1_at_13095,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_1_at_13095,{leo_pod_sup,start_link,[leo_rpc_client_manager_1_at_13095,16,16,leo_rpc_client_conn,[manager_1,"10.0.1.102",13095,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_10@10.16.2.223	2018-10-18 11:01:12.166537 +0800	1539831672	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:12.166857 +0800	1539831672	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:12.167021 +0800	1539831672	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15497.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:17.168417 +0800	1539831677	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:17.168798 +0800	1539831677	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:17.168954 +0800	1539831677	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15523.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:22.170394 +0800	1539831682	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:22.170918 +0800	1539831682	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:22.171110 +0800	1539831682	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15570.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:27.172363 +0800	1539831687	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:27.172896 +0800	1539831687	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:27.203140 +0800	1539831687	null:null	0	CRASH REPORT Process <0.15638.18> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_10@10.16.2.223	2018-10-18 11:01:27.203646 +0800	1539831687	null:null	0	Supervisor leo_rpc_client_manager_1_at_13095_sup had child leo_rpc_client_manager_1_at_13095 started with leo_pod_manager:start_link(leo_rpc_client_manager_1_at_13095, 16, 16, leo_rpc_client_conn, [manager_1,"10.0.1.102",13095,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_10@10.16.2.223	2018-10-18 11:01:27.203816 +0800	1539831687	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15592.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[W]	manager_10@10.16.2.223	2018-10-18 11:01:27.203967 +0800	1539831687	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_1_at_13095,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_1_at_13095,{leo_pod_sup,start_link,[leo_rpc_client_manager_1_at_13095,16,16,leo_rpc_client_conn,[manager_1,"10.0.1.102",13095,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_10@10.16.2.223	2018-10-18 11:01:32.205419 +0800	1539831692	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:32.205865 +0800	1539831692	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:32.206040 +0800	1539831692	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15641.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:37.207435 +0800	1539831697	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:37.207781 +0800	1539831697	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:37.207957 +0800	1539831697	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15666.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
[E]	manager_10@10.16.2.223	2018-10-18 11:01:42.209476 +0800	1539831702	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:call/2 line 204
[E]	manager_10@10.16.2.223	2018-10-18 11:01:42.209790 +0800	1539831702	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_10@10.16.2.223	2018-10-18 11:01:42.209946 +0800	1539831702	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.15712.18> exit with reason no such process or port in call to gen_server:call(<0.6644.17>, raw_status) in context child_terminated
